---
title: "Environmental variability and bet-hedging"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rstudioapi)
current_path <- getActiveDocumentContext()$path 
setwd(dirname(current_path)) # set working directory to location of this file
```

## Learning objectives

1. Connect environmental variability to changes in lambda
2. Compare populations with a range of growth rates and sensitivities to enviornmental variability
3. Model a population with a seed bank

*last lecture: unrestricted population growth*

*modeled environmental stocahsticity by making lambda vary from year to year*

*this is a workaround for measuring and modeling actual environmental variables*

## Spatial environmental variability

*on small scales, patchiness makes populations grow or shrink*

* example: light & understory species
* $\lambda$ varies in space
* accumulation in good patches
* lattice models, cells affect population growth

*draw 4x4 lattice, random patches and plants*

*lambda=0.9 or 1.1 to indicate where populations growing and shrinking*

## Temporal environmental variability

* example: climate
* $\lambda$ > 1 in wet years
* $\lambda$ < 1 in dry years

*species can avoid bad patches by dispersing into good patches - how might a species avoid bad years?*

## Bet-hedging and seed banks

*temporal analog to dealing with bad years*

* evolve to cope with environmental variability *in other words, variability is a selective agent*
* bet-hedging: lower variation in fitness, but lower overall fitness *growth*
* mechanism: seed banks
* low germination rate: more seeds in seed bank, spread risk *some seeds in reserve in case its a bad year to germinate*
* high germination rate: fewer seeds in seed bank, risky

*similar to gambling, if plants make small bets, keeping most chips (seeds) in reserve, less risky; if you make large bets, more risky, and it might pay out (like in a good year) or you might lose everything (go locally extinct)* 

## Demonstration of bet-hedging

*bet-hedging is a good strategy in the long run*

* low variance, low mean more beneficial than high variance, high mean

| Year | Population 1 | Population 2 |
| :--- | :--- | :--- |
| 1 | 0.2 | 0.8 |
| 2 | 3.0 | 1.2 |
| 3 | 0.4 | 0.9 |
| 4 | 2.5 | 1.1 |
| arithmetic mean | 0.42 | 0 |
|geometric mean | -0.12 | -0.01 |


## Modeling seed banks

*in lab, we'll model density independent growth with a seed bank*

* $\lambda$ = per capita growth rate
* N = number of seeds *for annual plant model*
* g = germination rate *of seeds produced by adults*
* s = survival of seeds in seed bank

$$ N_{t+1} = N(1-g)s + \lambda g N $$

* includes the seeds that go into the seed bank
* first term = seeds in seed bank
* second term = new seeds

